import { Poppins } from "next/font/google";
import "./globals.css";
import Footer1 from "./_components/Footer/Footer1";
import Header11 from "./_components/Header/Header11";

const inter = Poppins({ subsets: ["latin"], weight: "400"});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header11/>
        {children}
        <Footer1/>
      </body>
    </html>
  );
}
